# Generated by Django 3.2 on 2022-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Vendor'), ('2', 'Client')], max_length=10, null=True),
        ),
    ]
